# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerID', models.CharField(max_length=7)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('zipCode', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicesID', models.CharField(max_length=60)),
                ('needsID', models.CharField(max_length=60)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Customers')),
            ],
        ),
    ]
