# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Customer'),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='needsID',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='servicesID',
            field=models.CharField(max_length=600),
        ),
    ]
