# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bio',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerID',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='userName',
            field=models.CharField(max_length=200),
        ),
    ]
