# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 15:30
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
